name: Create Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'The next version of fvwm3 after this release: '
        required: true
      isDraft:
        description: 'Make a draft release, rather than an official release'
        type: boolean
        required: true
jobs:
  createrelease:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    container: fvwmorg/fvwm3-build:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Make workspace safe for git
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: Repo Settings
      run:  |
        git config --global user.name "Thomas Adam"
        git config --global user.email "thomas@fvwm.org"
    - name: Get Current Version (for release...)
      id: versionRelease
      run: |
        git fetch -q -n origin
        echo "versionRelease=$(git show HEAD:./.current-version)" >> $GITHUB_ENV
    - name: Build artefacts
      run: |
        meson setup --reconfigure compile -Dmandoc=true -Dhtmldoc=true -Dgolang=enabled && \
        meson compile -C compile && meson dist --formats gztar -C compile
    - name: Clone docs repository
      uses: actions/checkout@v4
      with:
        repository: fvwmorg/fvwmorg.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: fvwmorg.github.io
        fetch-depth: 0

    - name: Generate & Commit manpages on website
      working-directory: ./fvwmorg.github.io
      run: |
        set -euo pipefail
        ${GITHUB_WORKSPACE}/fvwm3/meson-scripts/generate-manpages-website.sh \
            ${GITHUB_WORKSPACE}/fvwmorg.github.io

        # Only commit/push if there are changes
        git add -A
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -a --author="Thomas Adam <thomas.adam@fvwm.org>" -m "[AUTO]: Update manpages for release ${{ env.versionRelease }}"
          git show
          git push origin --dry-run
        fi
